# EXP_NAME: 'YOUR_EXPERIMENT_NAME'
RNG_SEED: 1
DATASET:
  NAME: CIFAR10 
  ROOT_DIR: './data'
  VAL_RATIO: 0.1
  AUG_METHOD: 'hflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.025
  LR_POLICY: cos
  LR_MULT: 0.1
  # STEPS: [0, 60, 120, 160, 200] 
  MAX_EPOCH: 200 # for eval net 200 for embedding and 500 for images
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 100
  IM_SIZE: 32
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  INIT_L_RATIO: 0.
#  BUDGET_SIZE: 10
  # SAMPLING_FN: 'uncertainty'
  MAX_ITER: 32 # for active learning steps
  FINE_TUNE: False
  DELTA_RESOLUTION: 0.05
  MAX_DELTA: 1.1